//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"

	v1beta1 "github.com/projectsveltos/sveltosctl/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Snapshot)(nil), (*v1beta1.Snapshot)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Snapshot_To_v1beta1_Snapshot(a.(*Snapshot), b.(*v1beta1.Snapshot), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Snapshot)(nil), (*Snapshot)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Snapshot_To_v1alpha1_Snapshot(a.(*v1beta1.Snapshot), b.(*Snapshot), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SnapshotList)(nil), (*v1beta1.SnapshotList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SnapshotList_To_v1beta1_SnapshotList(a.(*SnapshotList), b.(*v1beta1.SnapshotList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SnapshotList)(nil), (*SnapshotList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SnapshotList_To_v1alpha1_SnapshotList(a.(*v1beta1.SnapshotList), b.(*SnapshotList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SnapshotSpec)(nil), (*v1beta1.SnapshotSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec(a.(*SnapshotSpec), b.(*v1beta1.SnapshotSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SnapshotSpec)(nil), (*SnapshotSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec(a.(*v1beta1.SnapshotSpec), b.(*SnapshotSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SnapshotStatus)(nil), (*v1beta1.SnapshotStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus(a.(*SnapshotStatus), b.(*v1beta1.SnapshotStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SnapshotStatus)(nil), (*SnapshotStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus(a.(*v1beta1.SnapshotStatus), b.(*SnapshotStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Snapshot_To_v1beta1_Snapshot(in *Snapshot, out *v1beta1.Snapshot, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Snapshot_To_v1beta1_Snapshot is an autogenerated conversion function.
func Convert_v1alpha1_Snapshot_To_v1beta1_Snapshot(in *Snapshot, out *v1beta1.Snapshot, s conversion.Scope) error {
	return autoConvert_v1alpha1_Snapshot_To_v1beta1_Snapshot(in, out, s)
}

func autoConvert_v1beta1_Snapshot_To_v1alpha1_Snapshot(in *v1beta1.Snapshot, out *Snapshot, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Snapshot_To_v1alpha1_Snapshot is an autogenerated conversion function.
func Convert_v1beta1_Snapshot_To_v1alpha1_Snapshot(in *v1beta1.Snapshot, out *Snapshot, s conversion.Scope) error {
	return autoConvert_v1beta1_Snapshot_To_v1alpha1_Snapshot(in, out, s)
}

func autoConvert_v1alpha1_SnapshotList_To_v1beta1_SnapshotList(in *SnapshotList, out *v1beta1.SnapshotList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.Snapshot)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_SnapshotList_To_v1beta1_SnapshotList is an autogenerated conversion function.
func Convert_v1alpha1_SnapshotList_To_v1beta1_SnapshotList(in *SnapshotList, out *v1beta1.SnapshotList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SnapshotList_To_v1beta1_SnapshotList(in, out, s)
}

func autoConvert_v1beta1_SnapshotList_To_v1alpha1_SnapshotList(in *v1beta1.SnapshotList, out *SnapshotList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Snapshot)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_SnapshotList_To_v1alpha1_SnapshotList is an autogenerated conversion function.
func Convert_v1beta1_SnapshotList_To_v1alpha1_SnapshotList(in *v1beta1.SnapshotList, out *SnapshotList, s conversion.Scope) error {
	return autoConvert_v1beta1_SnapshotList_To_v1alpha1_SnapshotList(in, out, s)
}

func autoConvert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec(in *SnapshotSpec, out *v1beta1.SnapshotSpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	out.StartingDeadlineSeconds = (*int64)(unsafe.Pointer(in.StartingDeadlineSeconds))
	out.Storage = in.Storage
	out.SuccessfulSnapshotLimit = (*int32)(unsafe.Pointer(in.SuccessfulSnapshotLimit))
	return nil
}

// Convert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec is an autogenerated conversion function.
func Convert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec(in *SnapshotSpec, out *v1beta1.SnapshotSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec(in, out, s)
}

func autoConvert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec(in *v1beta1.SnapshotSpec, out *SnapshotSpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	out.StartingDeadlineSeconds = (*int64)(unsafe.Pointer(in.StartingDeadlineSeconds))
	out.Storage = in.Storage
	out.SuccessfulSnapshotLimit = (*int32)(unsafe.Pointer(in.SuccessfulSnapshotLimit))
	return nil
}

// Convert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec is an autogenerated conversion function.
func Convert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec(in *v1beta1.SnapshotSpec, out *SnapshotSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec(in, out, s)
}

func autoConvert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus(in *SnapshotStatus, out *v1beta1.SnapshotStatus, s conversion.Scope) error {
	out.NextScheduleTime = (*v1.Time)(unsafe.Pointer(in.NextScheduleTime))
	out.LastRunTime = (*v1.Time)(unsafe.Pointer(in.LastRunTime))
	out.LastRunStatus = (*v1beta1.CollectionStatus)(unsafe.Pointer(in.LastRunStatus))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus is an autogenerated conversion function.
func Convert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus(in *SnapshotStatus, out *v1beta1.SnapshotStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus(in, out, s)
}

func autoConvert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus(in *v1beta1.SnapshotStatus, out *SnapshotStatus, s conversion.Scope) error {
	out.NextScheduleTime = (*v1.Time)(unsafe.Pointer(in.NextScheduleTime))
	out.LastRunTime = (*v1.Time)(unsafe.Pointer(in.LastRunTime))
	out.LastRunStatus = (*CollectionStatus)(unsafe.Pointer(in.LastRunStatus))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus is an autogenerated conversion function.
func Convert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus(in *v1beta1.SnapshotStatus, out *SnapshotStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus(in, out, s)
}
