//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"

	apiv1alpha1 "github.com/projectsveltos/libsveltos/api/v1alpha1"
	apiv1beta1 "github.com/projectsveltos/libsveltos/api/v1beta1"
	v1beta1 "github.com/projectsveltos/sveltosctl/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Log)(nil), (*v1beta1.Log)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Log_To_v1beta1_Log(a.(*Log), b.(*v1beta1.Log), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Log)(nil), (*Log)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Log_To_v1alpha1_Log(a.(*v1beta1.Log), b.(*Log), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Resource)(nil), (*v1beta1.Resource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Resource_To_v1beta1_Resource(a.(*Resource), b.(*v1beta1.Resource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Resource)(nil), (*Resource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Resource_To_v1alpha1_Resource(a.(*v1beta1.Resource), b.(*Resource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Snapshot)(nil), (*v1beta1.Snapshot)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Snapshot_To_v1beta1_Snapshot(a.(*Snapshot), b.(*v1beta1.Snapshot), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Snapshot)(nil), (*Snapshot)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Snapshot_To_v1alpha1_Snapshot(a.(*v1beta1.Snapshot), b.(*Snapshot), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SnapshotList)(nil), (*v1beta1.SnapshotList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SnapshotList_To_v1beta1_SnapshotList(a.(*SnapshotList), b.(*v1beta1.SnapshotList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SnapshotList)(nil), (*SnapshotList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SnapshotList_To_v1alpha1_SnapshotList(a.(*v1beta1.SnapshotList), b.(*SnapshotList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SnapshotSpec)(nil), (*v1beta1.SnapshotSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec(a.(*SnapshotSpec), b.(*v1beta1.SnapshotSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SnapshotSpec)(nil), (*SnapshotSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec(a.(*v1beta1.SnapshotSpec), b.(*SnapshotSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SnapshotStatus)(nil), (*v1beta1.SnapshotStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus(a.(*SnapshotStatus), b.(*v1beta1.SnapshotStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SnapshotStatus)(nil), (*SnapshotStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus(a.(*v1beta1.SnapshotStatus), b.(*SnapshotStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Techsupport)(nil), (*v1beta1.Techsupport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Techsupport_To_v1beta1_Techsupport(a.(*Techsupport), b.(*v1beta1.Techsupport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Techsupport)(nil), (*Techsupport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Techsupport_To_v1alpha1_Techsupport(a.(*v1beta1.Techsupport), b.(*Techsupport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TechsupportList)(nil), (*v1beta1.TechsupportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TechsupportList_To_v1beta1_TechsupportList(a.(*TechsupportList), b.(*v1beta1.TechsupportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TechsupportList)(nil), (*TechsupportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TechsupportList_To_v1alpha1_TechsupportList(a.(*v1beta1.TechsupportList), b.(*TechsupportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TechsupportStatus)(nil), (*v1beta1.TechsupportStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TechsupportStatus_To_v1beta1_TechsupportStatus(a.(*TechsupportStatus), b.(*v1beta1.TechsupportStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TechsupportStatus)(nil), (*TechsupportStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TechsupportStatus_To_v1alpha1_TechsupportStatus(a.(*v1beta1.TechsupportStatus), b.(*TechsupportStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*TechsupportSpec)(nil), (*v1beta1.TechsupportSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TechsupportSpec_To_v1beta1_TechsupportSpec(a.(*TechsupportSpec), b.(*v1beta1.TechsupportSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.TechsupportSpec)(nil), (*TechsupportSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TechsupportSpec_To_v1alpha1_TechsupportSpec(a.(*v1beta1.TechsupportSpec), b.(*TechsupportSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Log_To_v1beta1_Log(in *Log, out *v1beta1.Log, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.LabelFilters = *(*[]apiv1beta1.LabelFilter)(unsafe.Pointer(&in.LabelFilters))
	out.SinceSeconds = (*int64)(unsafe.Pointer(in.SinceSeconds))
	return nil
}

// Convert_v1alpha1_Log_To_v1beta1_Log is an autogenerated conversion function.
func Convert_v1alpha1_Log_To_v1beta1_Log(in *Log, out *v1beta1.Log, s conversion.Scope) error {
	return autoConvert_v1alpha1_Log_To_v1beta1_Log(in, out, s)
}

func autoConvert_v1beta1_Log_To_v1alpha1_Log(in *v1beta1.Log, out *Log, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.LabelFilters = *(*[]apiv1alpha1.LabelFilter)(unsafe.Pointer(&in.LabelFilters))
	out.SinceSeconds = (*int64)(unsafe.Pointer(in.SinceSeconds))
	return nil
}

// Convert_v1beta1_Log_To_v1alpha1_Log is an autogenerated conversion function.
func Convert_v1beta1_Log_To_v1alpha1_Log(in *v1beta1.Log, out *Log, s conversion.Scope) error {
	return autoConvert_v1beta1_Log_To_v1alpha1_Log(in, out, s)
}

func autoConvert_v1alpha1_Resource_To_v1beta1_Resource(in *Resource, out *v1beta1.Resource, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Group = in.Group
	out.Version = in.Version
	out.Kind = in.Kind
	out.LabelFilters = *(*[]apiv1beta1.LabelFilter)(unsafe.Pointer(&in.LabelFilters))
	return nil
}

// Convert_v1alpha1_Resource_To_v1beta1_Resource is an autogenerated conversion function.
func Convert_v1alpha1_Resource_To_v1beta1_Resource(in *Resource, out *v1beta1.Resource, s conversion.Scope) error {
	return autoConvert_v1alpha1_Resource_To_v1beta1_Resource(in, out, s)
}

func autoConvert_v1beta1_Resource_To_v1alpha1_Resource(in *v1beta1.Resource, out *Resource, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Group = in.Group
	out.Version = in.Version
	out.Kind = in.Kind
	out.LabelFilters = *(*[]apiv1alpha1.LabelFilter)(unsafe.Pointer(&in.LabelFilters))
	return nil
}

// Convert_v1beta1_Resource_To_v1alpha1_Resource is an autogenerated conversion function.
func Convert_v1beta1_Resource_To_v1alpha1_Resource(in *v1beta1.Resource, out *Resource, s conversion.Scope) error {
	return autoConvert_v1beta1_Resource_To_v1alpha1_Resource(in, out, s)
}

func autoConvert_v1alpha1_Snapshot_To_v1beta1_Snapshot(in *Snapshot, out *v1beta1.Snapshot, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Snapshot_To_v1beta1_Snapshot is an autogenerated conversion function.
func Convert_v1alpha1_Snapshot_To_v1beta1_Snapshot(in *Snapshot, out *v1beta1.Snapshot, s conversion.Scope) error {
	return autoConvert_v1alpha1_Snapshot_To_v1beta1_Snapshot(in, out, s)
}

func autoConvert_v1beta1_Snapshot_To_v1alpha1_Snapshot(in *v1beta1.Snapshot, out *Snapshot, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Snapshot_To_v1alpha1_Snapshot is an autogenerated conversion function.
func Convert_v1beta1_Snapshot_To_v1alpha1_Snapshot(in *v1beta1.Snapshot, out *Snapshot, s conversion.Scope) error {
	return autoConvert_v1beta1_Snapshot_To_v1alpha1_Snapshot(in, out, s)
}

func autoConvert_v1alpha1_SnapshotList_To_v1beta1_SnapshotList(in *SnapshotList, out *v1beta1.SnapshotList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.Snapshot)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_SnapshotList_To_v1beta1_SnapshotList is an autogenerated conversion function.
func Convert_v1alpha1_SnapshotList_To_v1beta1_SnapshotList(in *SnapshotList, out *v1beta1.SnapshotList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SnapshotList_To_v1beta1_SnapshotList(in, out, s)
}

func autoConvert_v1beta1_SnapshotList_To_v1alpha1_SnapshotList(in *v1beta1.SnapshotList, out *SnapshotList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Snapshot)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_SnapshotList_To_v1alpha1_SnapshotList is an autogenerated conversion function.
func Convert_v1beta1_SnapshotList_To_v1alpha1_SnapshotList(in *v1beta1.SnapshotList, out *SnapshotList, s conversion.Scope) error {
	return autoConvert_v1beta1_SnapshotList_To_v1alpha1_SnapshotList(in, out, s)
}

func autoConvert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec(in *SnapshotSpec, out *v1beta1.SnapshotSpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	out.StartingDeadlineSeconds = (*int64)(unsafe.Pointer(in.StartingDeadlineSeconds))
	out.Storage = in.Storage
	out.SuccessfulSnapshotLimit = (*int32)(unsafe.Pointer(in.SuccessfulSnapshotLimit))
	return nil
}

// Convert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec is an autogenerated conversion function.
func Convert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec(in *SnapshotSpec, out *v1beta1.SnapshotSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SnapshotSpec_To_v1beta1_SnapshotSpec(in, out, s)
}

func autoConvert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec(in *v1beta1.SnapshotSpec, out *SnapshotSpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	out.StartingDeadlineSeconds = (*int64)(unsafe.Pointer(in.StartingDeadlineSeconds))
	out.Storage = in.Storage
	out.SuccessfulSnapshotLimit = (*int32)(unsafe.Pointer(in.SuccessfulSnapshotLimit))
	return nil
}

// Convert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec is an autogenerated conversion function.
func Convert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec(in *v1beta1.SnapshotSpec, out *SnapshotSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_SnapshotSpec_To_v1alpha1_SnapshotSpec(in, out, s)
}

func autoConvert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus(in *SnapshotStatus, out *v1beta1.SnapshotStatus, s conversion.Scope) error {
	out.NextScheduleTime = (*v1.Time)(unsafe.Pointer(in.NextScheduleTime))
	out.LastRunTime = (*v1.Time)(unsafe.Pointer(in.LastRunTime))
	out.LastRunStatus = (*v1beta1.CollectionStatus)(unsafe.Pointer(in.LastRunStatus))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus is an autogenerated conversion function.
func Convert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus(in *SnapshotStatus, out *v1beta1.SnapshotStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SnapshotStatus_To_v1beta1_SnapshotStatus(in, out, s)
}

func autoConvert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus(in *v1beta1.SnapshotStatus, out *SnapshotStatus, s conversion.Scope) error {
	out.NextScheduleTime = (*v1.Time)(unsafe.Pointer(in.NextScheduleTime))
	out.LastRunTime = (*v1.Time)(unsafe.Pointer(in.LastRunTime))
	out.LastRunStatus = (*CollectionStatus)(unsafe.Pointer(in.LastRunStatus))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus is an autogenerated conversion function.
func Convert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus(in *v1beta1.SnapshotStatus, out *SnapshotStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_SnapshotStatus_To_v1alpha1_SnapshotStatus(in, out, s)
}

func autoConvert_v1alpha1_Techsupport_To_v1beta1_Techsupport(in *Techsupport, out *v1beta1.Techsupport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TechsupportSpec_To_v1beta1_TechsupportSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TechsupportStatus_To_v1beta1_TechsupportStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Techsupport_To_v1beta1_Techsupport is an autogenerated conversion function.
func Convert_v1alpha1_Techsupport_To_v1beta1_Techsupport(in *Techsupport, out *v1beta1.Techsupport, s conversion.Scope) error {
	return autoConvert_v1alpha1_Techsupport_To_v1beta1_Techsupport(in, out, s)
}

func autoConvert_v1beta1_Techsupport_To_v1alpha1_Techsupport(in *v1beta1.Techsupport, out *Techsupport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_TechsupportSpec_To_v1alpha1_TechsupportSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_TechsupportStatus_To_v1alpha1_TechsupportStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Techsupport_To_v1alpha1_Techsupport is an autogenerated conversion function.
func Convert_v1beta1_Techsupport_To_v1alpha1_Techsupport(in *v1beta1.Techsupport, out *Techsupport, s conversion.Scope) error {
	return autoConvert_v1beta1_Techsupport_To_v1alpha1_Techsupport(in, out, s)
}

func autoConvert_v1alpha1_TechsupportList_To_v1beta1_TechsupportList(in *TechsupportList, out *v1beta1.TechsupportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.Techsupport, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Techsupport_To_v1beta1_Techsupport(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_TechsupportList_To_v1beta1_TechsupportList is an autogenerated conversion function.
func Convert_v1alpha1_TechsupportList_To_v1beta1_TechsupportList(in *TechsupportList, out *v1beta1.TechsupportList, s conversion.Scope) error {
	return autoConvert_v1alpha1_TechsupportList_To_v1beta1_TechsupportList(in, out, s)
}

func autoConvert_v1beta1_TechsupportList_To_v1alpha1_TechsupportList(in *v1beta1.TechsupportList, out *TechsupportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Techsupport, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Techsupport_To_v1alpha1_Techsupport(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_TechsupportList_To_v1alpha1_TechsupportList is an autogenerated conversion function.
func Convert_v1beta1_TechsupportList_To_v1alpha1_TechsupportList(in *v1beta1.TechsupportList, out *TechsupportList, s conversion.Scope) error {
	return autoConvert_v1beta1_TechsupportList_To_v1alpha1_TechsupportList(in, out, s)
}

func autoConvert_v1alpha1_TechsupportSpec_To_v1beta1_TechsupportSpec(in *TechsupportSpec, out *v1beta1.TechsupportSpec, s conversion.Scope) error {
	// WARNING: in.ClusterSelector requires manual conversion: inconvertible types (github.com/projectsveltos/libsveltos/api/v1alpha1.Selector vs github.com/projectsveltos/libsveltos/api/v1beta1.Selector)
	out.Resources = *(*[]v1beta1.Resource)(unsafe.Pointer(&in.Resources))
	out.Logs = *(*[]v1beta1.Log)(unsafe.Pointer(&in.Logs))
	out.Tar = in.Tar
	out.Schedule = in.Schedule
	out.StartingDeadlineSeconds = (*int64)(unsafe.Pointer(in.StartingDeadlineSeconds))
	out.Storage = in.Storage
	out.SuccessfulTechsupportLimit = (*int32)(unsafe.Pointer(in.SuccessfulTechsupportLimit))
	return nil
}

func autoConvert_v1beta1_TechsupportSpec_To_v1alpha1_TechsupportSpec(in *v1beta1.TechsupportSpec, out *TechsupportSpec, s conversion.Scope) error {
	// WARNING: in.ClusterSelector requires manual conversion: inconvertible types (github.com/projectsveltos/libsveltos/api/v1beta1.Selector vs github.com/projectsveltos/libsveltos/api/v1alpha1.Selector)
	out.Resources = *(*[]Resource)(unsafe.Pointer(&in.Resources))
	out.Logs = *(*[]Log)(unsafe.Pointer(&in.Logs))
	out.Tar = in.Tar
	out.Schedule = in.Schedule
	out.StartingDeadlineSeconds = (*int64)(unsafe.Pointer(in.StartingDeadlineSeconds))
	out.Storage = in.Storage
	out.SuccessfulTechsupportLimit = (*int32)(unsafe.Pointer(in.SuccessfulTechsupportLimit))
	return nil
}

func autoConvert_v1alpha1_TechsupportStatus_To_v1beta1_TechsupportStatus(in *TechsupportStatus, out *v1beta1.TechsupportStatus, s conversion.Scope) error {
	out.NextScheduleTime = (*v1.Time)(unsafe.Pointer(in.NextScheduleTime))
	out.LastRunTime = (*v1.Time)(unsafe.Pointer(in.LastRunTime))
	out.LastRunStatus = (*v1beta1.CollectionStatus)(unsafe.Pointer(in.LastRunStatus))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.MatchingClusterRefs = *(*[]corev1.ObjectReference)(unsafe.Pointer(&in.MatchingClusterRefs))
	return nil
}

// Convert_v1alpha1_TechsupportStatus_To_v1beta1_TechsupportStatus is an autogenerated conversion function.
func Convert_v1alpha1_TechsupportStatus_To_v1beta1_TechsupportStatus(in *TechsupportStatus, out *v1beta1.TechsupportStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_TechsupportStatus_To_v1beta1_TechsupportStatus(in, out, s)
}

func autoConvert_v1beta1_TechsupportStatus_To_v1alpha1_TechsupportStatus(in *v1beta1.TechsupportStatus, out *TechsupportStatus, s conversion.Scope) error {
	out.NextScheduleTime = (*v1.Time)(unsafe.Pointer(in.NextScheduleTime))
	out.LastRunTime = (*v1.Time)(unsafe.Pointer(in.LastRunTime))
	out.LastRunStatus = (*CollectionStatus)(unsafe.Pointer(in.LastRunStatus))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.MatchingClusterRefs = *(*[]corev1.ObjectReference)(unsafe.Pointer(&in.MatchingClusterRefs))
	return nil
}

// Convert_v1beta1_TechsupportStatus_To_v1alpha1_TechsupportStatus is an autogenerated conversion function.
func Convert_v1beta1_TechsupportStatus_To_v1alpha1_TechsupportStatus(in *v1beta1.TechsupportStatus, out *TechsupportStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_TechsupportStatus_To_v1alpha1_TechsupportStatus(in, out, s)
}
